// This code was generated by GenerateDataObjects
package net.sf.borg.model.beans;



public class Subtask extends KeyedBean implements java.io.Serializable {

	private Integer Id_;
	public Integer getId() { return( Id_ ); }
	public void setId( Integer xx ){ Id_ = xx; }

	private java.util.Date CreateDate_;
	public java.util.Date getCreateDate() { return( CreateDate_ ); }
	public void setCreateDate( java.util.Date xx ){ CreateDate_ = xx; }

	private java.util.Date CloseDate_;
	public java.util.Date getCloseDate() { return( CloseDate_ ); }
	public void setCloseDate( java.util.Date xx ){ CloseDate_ = xx; }

	private java.util.Date DueDate_;
	public java.util.Date getDueDate() { return( DueDate_ ); }
	public void setDueDate( java.util.Date xx ){ DueDate_ = xx; }

	private String Description_;
	public String getDescription() { return( Description_ ); }
	public void setDescription( String xx ){ Description_ = xx; }

	private Integer Task_;
	public Integer getTask() { return( Task_ ); }
	public void setTask( Integer xx ){ Task_ = xx; }

	protected Object clone() {
		Subtask dst = new Subtask();
		dst.setKey( getKey());
		dst.setId( getId() );
		dst.setCreateDate( getCreateDate() );
		dst.setCloseDate( getCloseDate() );
		dst.setDueDate( getDueDate() );
		dst.setDescription( getDescription() );
		dst.setTask( getTask() );
		return(dst);
	}
}
