// This code was generated by GenerateDataObjects
package net.sf.borg.model.beans;



public class Link extends KeyedBean implements java.io.Serializable {

	private Integer ownerKey;
	private String ownerType;
	private String path;
	private String linkType;
	
	protected Object clone() {
		Link dst = new Link();
		dst.setKey( getKey());
		dst.setLinkType(getLinkType());
		dst.setOwnerKey( getOwnerKey() );
		dst.setOwnerType( getOwnerType() );
		dst.setPath( getPath() );
		return(dst);
	}
	public Integer getOwnerKey() {
		return ownerKey;
	}
	public void setOwnerKey(Integer ownerKey) {
		this.ownerKey = ownerKey;
	}
	public String getOwnerType() {
		return ownerType;
	}
	public void setOwnerType(String ownerType) {
		this.ownerType = ownerType;
	}
	public String getPath() {
		return path;
	}
	public void setPath(String path) {
		this.path = path;
	}
	public String getLinkType() {
		return linkType;
	}
	public void setLinkType(String linkType) {
		this.linkType = linkType;
	}
	
}
