// This code was generated by GenerateDataObjects
package net.sf.borg.model.beans;



public class Memo extends KeyedBean implements java.io.Serializable {

	private String MemoName_;
	public String getMemoName() { return( MemoName_ ); }
	public void setMemoName( String xx ){ MemoName_ = xx; }

	private String MemoText_;
	public String getMemoText() { return( MemoText_ ); }
	public void setMemoText( String xx ){ MemoText_ = xx; }

	private Integer PalmId_;
	public Integer getPalmId() { return( PalmId_ ); }
	public void setPalmId( Integer xx ){ PalmId_ = xx; }

	private boolean New_;
	public boolean getNew() { return( New_ ); }
	public void setNew( boolean xx ){ New_ = xx; }

	private boolean Modified_;
	public boolean getModified() { return( Modified_ ); }
	public void setModified( boolean xx ){ Modified_ = xx; }

	private boolean Deleted_;
	public boolean getDeleted() { return( Deleted_ ); }
	public void setDeleted( boolean xx ){ Deleted_ = xx; }

	private boolean Private_;
	public boolean getPrivate() { return( Private_ ); }
	public void setPrivate( boolean xx ){ Private_ = xx; }

	protected Object clone() {
		Memo dst = new Memo();
		dst.setKey( getKey());
		dst.setMemoName( getMemoName() );
		dst.setMemoText( getMemoText() );
		dst.setPalmId( getPalmId() );
		dst.setNew( getNew() );
		dst.setModified( getModified() );
		dst.setDeleted( getDeleted() );
		dst.setPrivate( getPrivate() );
		return(dst);
	}
}
