// This code was generated by GenerateDataObjects
package net.sf.borg.model.beans;



public class Project extends KeyedBean implements java.io.Serializable {

	private Integer Id_;
	public Integer getId() { return( Id_ ); }
	public void setId( Integer xx ){ Id_ = xx; }

	private java.util.Date StartDate_;
	public java.util.Date getStartDate() { return( StartDate_ ); }
	public void setStartDate( java.util.Date xx ){ StartDate_ = xx; }

	private java.util.Date DueDate_;
	public java.util.Date getDueDate() { return( DueDate_ ); }
	public void setDueDate( java.util.Date xx ){ DueDate_ = xx; }

	private String Description_;
	public String getDescription() { return( Description_ ); }
	public void setDescription( String xx ){ Description_ = xx; }

	private String Category_;
	public String getCategory() { return( Category_ ); }
	public void setCategory( String xx ){ Category_ = xx; }

	private String Status_;
	public String getStatus() { return( Status_ ); }
	public void setStatus( String xx ){ Status_ = xx; }
	
	private Integer parent_;
	public Integer getParent() {
	    return parent_;
	}
	public void setParent(Integer parent) {
	    this.parent_ = parent;
	}

	protected Object clone() {
		Project dst = new Project();
		dst.setKey( getKey());
		dst.setId( getId() );
		dst.setStartDate( getStartDate() );
		dst.setDueDate( getDueDate() );
		dst.setDescription( getDescription() );
		dst.setCategory( getCategory() );
		dst.setStatus( getStatus() );
		dst.setParent(getParent());
		return(dst);
	}
	
}
