// This code was generated by GenerateDataObjects
package net.sf.borg.model.beans;

import net.sf.borg.common.XTree;
public class TaskXMLAdapter extends BeanXMLAdapter<Task> {

	public XTree toXml( Task o )
	{
		
		XTree xt = new XTree();
		xt.name("Task");
		xt.appendChild("KEY", Integer.toString(o.getKey()));
		if( o.getTaskNumber() != null )
			xt.appendChild("TaskNumber", BeanXMLAdapter.toString(o.getTaskNumber()));
		if( o.getStartDate() != null )
			xt.appendChild("StartDate", BeanXMLAdapter.toString(o.getStartDate()));
		if( o.getCD() != null )
			xt.appendChild("CD", BeanXMLAdapter.toString(o.getCD()));
		if( o.getDueDate() != null )
			xt.appendChild("DueDate", BeanXMLAdapter.toString(o.getDueDate()));
		if( o.getET() != null )
			xt.appendChild("ET", BeanXMLAdapter.toString(o.getET()));
		if( o.getPersonAssigned() != null && !o.getPersonAssigned().equals(""))
			xt.appendChild("PersonAssigned", o.getPersonAssigned());
		if( o.getPriority() != null )
			xt.appendChild("Priority", BeanXMLAdapter.toString(o.getPriority()));
		if( o.getState() != null && !o.getState().equals(""))
			xt.appendChild("State", o.getState());
		if( o.getType() != null && !o.getType().equals(""))
			xt.appendChild("Type", o.getType());
		if( o.getDescription() != null && !o.getDescription().equals(""))
			xt.appendChild("Description", o.getDescription());
		if( o.getResolution() != null && !o.getResolution().equals(""))
			xt.appendChild("Resolution", o.getResolution());
		if( o.getTodoList() != null && !o.getTodoList().equals(""))
			xt.appendChild("TodoList", o.getTodoList());
		if( o.getUserTask1() != null && !o.getUserTask1().equals(""))
			xt.appendChild("UserTask1", o.getUserTask1());
		if( o.getUserTask2() != null && !o.getUserTask2().equals(""))
			xt.appendChild("UserTask2", o.getUserTask2());
		if( o.getUserTask3() != null && !o.getUserTask3().equals(""))
			xt.appendChild("UserTask3", o.getUserTask3());
		if( o.getUserTask4() != null && !o.getUserTask4().equals(""))
			xt.appendChild("UserTask4", o.getUserTask4());
		if( o.getUserTask5() != null && !o.getUserTask5().equals(""))
			xt.appendChild("UserTask5", o.getUserTask5());
		if( o.getCategory() != null && !o.getCategory().equals(""))
			xt.appendChild("Category", o.getCategory());
		if( o.getProject() != null )
			xt.appendChild("Project", BeanXMLAdapter.toString(o.getProject()));
		return( xt );
	}

	public Task fromXml( XTree xt )
	{
		Task ret = new Task();
		String ks = xt.child("KEY").value();
		ret.setKey( BeanXMLAdapter.toInt(ks) );
		String val = "";
		val = xt.child("TaskNumber").value();
		ret.setTaskNumber( BeanXMLAdapter.toInteger(val) );
		val = xt.child("StartDate").value();
		ret.setStartDate( BeanXMLAdapter.toDate(val) );
		val = xt.child("CD").value();
		ret.setCD( BeanXMLAdapter.toDate(val) );
		val = xt.child("DueDate").value();
		ret.setDueDate( BeanXMLAdapter.toDate(val) );
		val = xt.child("ET").value();
		ret.setET( BeanXMLAdapter.toDate(val) );
		val = xt.child("PersonAssigned").value();
		if( !val.equals("") )
			ret.setPersonAssigned( val );
		val = xt.child("Priority").value();
		ret.setPriority( BeanXMLAdapter.toInteger(val) );
		val = xt.child("State").value();
		if( !val.equals("") )
			ret.setState( val );
		val = xt.child("Type").value();
		if( !val.equals("") )
			ret.setType( val );
		val = xt.child("Description").value();
		if( !val.equals("") )
			ret.setDescription( val );
		val = xt.child("Resolution").value();
		if( !val.equals("") )
			ret.setResolution( val );
		val = xt.child("TodoList").value();
		if( !val.equals("") )
			ret.setTodoList( val );
		val = xt.child("UserTask1").value();
		if( !val.equals("") )
			ret.setUserTask1( val );
		val = xt.child("UserTask2").value();
		if( !val.equals("") )
			ret.setUserTask2( val );
		val = xt.child("UserTask3").value();
		if( !val.equals("") )
			ret.setUserTask3( val );
		val = xt.child("UserTask4").value();
		if( !val.equals("") )
			ret.setUserTask4( val );
		val = xt.child("UserTask5").value();
		if( !val.equals("") )
			ret.setUserTask5( val );
		val = xt.child("Category").value();
		if( !val.equals("") )
			ret.setCategory( val );
		val = xt.child("Project").value();
		ret.setProject( BeanXMLAdapter.toInteger(val) );
		return( ret );
	}
}
