// This code was generated by GenerateDataObjects
package net.sf.borg.model.beans;



public class Tasklog extends KeyedBean<Tasklog> implements java.io.Serializable {


	private static final long serialVersionUID = -7296390517941361874L;
	private Integer Id_;
	public Integer getId() { return( Id_ ); }
	public void setId( Integer xx ){ Id_ = xx; }

	private java.util.Date logTime_;
	public java.util.Date getlogTime() { return( logTime_ ); }
	public void setlogTime( java.util.Date xx ){ logTime_ = xx; }

	private String Description_;
	public String getDescription() { return( Description_ ); }
	public void setDescription( String xx ){ Description_ = xx; }

	private Integer Task_;
	public Integer getTask() { return( Task_ ); }
	public void setTask( Integer xx ){ Task_ = xx; }

	protected Tasklog clone() {
		Tasklog dst = new Tasklog();
		dst.setKey( getKey());
		dst.setId( getId() );
		dst.setlogTime( getlogTime() );
		dst.setDescription( getDescription() );
		dst.setTask( getTask() );
		return(dst);
	}
}
