// This code was generated by GenerateDataObjects
package net.sf.borg.model.db.file;

import net.sf.borg.model.beans.Appointment;
import net.sf.borg.model.beans.KeyedBean;
import net.sf.borg.model.db.file.mdb.Row;
import net.sf.borg.model.db.file.mdb.Schema;
public class AppointmentAdapter implements FileBeanAdapter {

	public KeyedBean fromRow( Row r ) throws Exception
	{
		Appointment ret = new Appointment();
		ret.setKey(r.getKey());
		ret.setDate( r.getDate("DT"));
		ret.setDuration( r.getInteger("DU"));
		ret.setText( r.getString("TX"));
		ret.setSkipList( r.getStringVector("SK"));
		ret.setNextTodo( r.getDate("NT"));
		ret.setSN( r.getInteger("SN"));
		ret.setVacation( r.getInteger("VC"));
		ret.setHoliday( r.getInteger("HD"));
		ret.setPrivate( r.getFlag(3));
		ret.setTimes( r.getInteger("TM"));
		ret.setFrequency( r.getString("RP"));
		ret.setTodo( r.getFlag(2));
		ret.setColor( r.getString("CL"));
		ret.setRepeatFlag( r.getFlag(1));
		ret.setCategory( r.getString("CAT"));
		ret.setNew( r.getFlag(4));
		ret.setModified( r.getFlag(5));
		ret.setDeleted( r.getFlag(6));
		ret.setAlarm( r.getString("ALM"));
		ret.setReminderTimes( r.getString("REM"));
		return( ret );
	}

	public Row toRow( Schema sch, KeyedBean b, boolean normalize ) throws Exception
	{
		Appointment o = (Appointment) b;
		Row ret = new Row(sch);
		ret.normalize(normalize);
		ret.setKey(o.getKey());
		ret.setField("DT", o.getDate());
		ret.setField("DU", o.getDuration());
		ret.setField("TX", o.getText());
		ret.setField("SK", o.getSkipList());
		ret.setField("NT", o.getNextTodo());
		ret.setField("SN", o.getSN());
		ret.setField("VC", o.getVacation());
		ret.setField("HD", o.getHoliday());
		ret.setFlag(3,  o.getPrivate());
		ret.setField("TM", o.getTimes());
		ret.setField("RP", o.getFrequency());
		ret.setFlag(2,  o.getTodo());
		ret.setField("CL", o.getColor());
		ret.setFlag(1,  o.getRepeatFlag());
		ret.setField("CAT", o.getCategory());
		ret.setFlag(4,  o.getNew());
		ret.setFlag(5,  o.getModified());
		ret.setFlag(6,  o.getDeleted());
		ret.setField("ALM", o.getAlarm());
		ret.setField("REM", o.getReminderTimes());
		return( ret );
	}

	public KeyedBean newBean() {
		return( new Appointment());
	}
}
