// This code was generated by GenerateDataObjects
package net.sf.borg.model;


import net.sf.borg.model.db.KeyedBean;

public class User extends KeyedBean implements java.io.Serializable {

	private String UserName_;
	public String getUserName() { return( UserName_ ); }
	public void setUserName( String xx ){ UserName_ = xx; }

	private String Password_;
	public String getPassword() { return( Password_ ); }
	public void setPassword( String xx ){ Password_ = xx; }

	private Integer UserId_;
	public Integer getUserId() { return( UserId_ ); }
	public void setUserId( Integer xx ){ UserId_ = xx; }

	protected Object clone() {
		User dst = new User();
		dst.setKey( getKey());
		dst.setUserName( getUserName() );
		dst.setPassword( getPassword() );
		dst.setUserId( getUserId() );
		return(dst);
	}
}
