<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE helpset PUBLIC "-//Sun Microsystems Inc.//DTD JavaHelp HelpSet Version 1.0//EN" "http://java.sun.com/products/javahelp/helpset_1_0.dtd"><!--generated by JHelpDev Version: 0.27-03/03/04, see jhelpdev.sourceforge.org-->

<helpset version="1.0">
 <title>
Help
 </title>
 <maps>
  <homeID>
top
  </homeID>
  <mapref location="default/Map.jhm"/>

 </maps>
 <view>
  <name>
TOC
  </name>
  <label>
TOC
  </label>
  <type>
javax.help.TOCView
  </type>
  <data>
default/BorgHelpTOC.xml
  </data>
 </view>
 <!--
 <view>
  <name>
Search
  </name>
  <label>
Search
  </label>
  <type>
javax.help.SearchView
  </type>
  <data engine="com.sun.java.help.search.DefaultSearchEngine">
JavaHelpSearch
  </data>
 </view>
 -->
</helpset>
